/*
 * This source file was generated by the Gradle 'init' task
 */

import org.junit.Test;

import game.Board;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        Board classUnderTest = new Board();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
